language: node_js
node_js:
  - "8"
notifications:
  email: false
sudo: false
addons:
  apt:
    packages:
    - expect
after_success:
  - npm run coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
